{
 "title": "Dev SDC Processing",
 "description": "This is a dashboard to track the SDC File Processing Pipeline",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Files Sorted\nNumber of Files Put/Sorted to Each Bucket within the last 24 hours.\n"
   },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 19, "x": 5, "y": 0 },
   "options": {
    "content": "\n# Files Processed\nOf Files Processed in Each Instrument Bucket within the last 24 hours"
   },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Files recieved to Incoming",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND (destination_bucket='dev-swsoc-incoming' AND action_type='PUT') ORDER BY time DESC \n\n",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 3 },
   "options": {
    "content": "\n\n### Total Processed from Level: `l0` -> `l1`\n"
   },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "options": {
    "content": "\n\n\n\n### Total Processed from Level: `l1` -> `ql`\n"
   },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 3 },
   "options": {
    "content": "\n### Total Across all Instrument Buckets:\n"
   },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "NEMISIS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-nemisis' AND destination_bucket='dev-hermes-nemisis' AND new_file_key LIKE 'l1/%' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "SPAN-I",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-spani' AND destination_bucket='dev-hermes-spani' AND new_file_key LIKE 'l1/%' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "NEMISIS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-nemisis' AND destination_bucket='dev-hermes-nemisis' AND new_file_key LIKE 'ql/%' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "SPAN-I",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-spani' AND destination_bucket='dev-hermes-spani' AND new_file_key LIKE 'ql/%' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "NEMISIS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-nemisis' AND destination_bucket='dev-hermes-nemisis' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "SPAN-I",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-spani' AND destination_bucket='dev-hermes-spani' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "NEMISIS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-swsoc-incoming' AND destination_bucket='dev-hermes-nemisis'",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "SPAN-I",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-swsoc-incoming' AND destination_bucket='dev-hermes-spani'",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "EEA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-eea' AND destination_bucket='dev-hermes-eea' AND new_file_key LIKE 'l1/%' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "MERIT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-merit' AND destination_bucket='dev-hermes-merit' AND new_file_key LIKE 'l1/%' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "EEA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-eea' AND destination_bucket='dev-hermes-eea' AND new_file_key LIKE 'ql/%' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "MERIT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-merit' AND destination_bucket='dev-hermes-merit' AND new_file_key LIKE 'ql/%' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "EEA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-eea' AND destination_bucket='dev-hermes-eea' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "MERIT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-hermes-merit' AND destination_bucket='dev-hermes-merit' ORDER BY time ",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "EEA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-swsoc-incoming' AND destination_bucket='dev-hermes-eea'",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "MERIT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT LICENSE README.md backup_dashboards.sh dashboards FROM $__database.$__table WHERE $__timeFilter AND source_bucket='dev-swsoc-incoming' AND destination_bucket='dev-hermes-merit'",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "Last File Synced to Incoming",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT file_key FROM $__database.$__table WHERE $__timeFilter AND destination_bucket='dev-swsoc-incoming' AND action_type='PUT' ORDER BY time DESC LIMIT 1",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "Last File Processed to Level 1 (l1)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "-- SELECT new_file_key FROM \"sdc_aws_logs\".\"sdc_aws_s3_bucket_log_table\" WHERE new_file_key LIKE 'l1/%' ORDER BY time DESC\nSELECT LICENSE README.md backup_dashboards.sh dashboards FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE new_file_key LIKE 'l1/%' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "Last File Processed to Quick Look (ql)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT new_file_key FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE new_file_key LIKE 'ql/%' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "SPAN-I Proccesed Files",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND source_bucket='dev-hermes-spani' AND destination_bucket='dev-hermes-spani' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "Files Synced to Incoming",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 15 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as synced_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND destination_bucket='dev-swsoc-incoming' AND action_type='PUT' ORDER BY time DESC\n",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "SPAN-I Proccesed Files",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 15 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND new_file_key LIKE 'l1/%' AND source_bucket='dev-hermes-spani' AND destination_bucket='dev-hermes-spani' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "SPAN-I Proccesed Files",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND new_file_key LIKE 'ql/%' AND source_bucket='dev-hermes-spani' AND destination_bucket='dev-hermes-spani' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "NEMISIS Proccesed Files",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND source_bucket='dev-hermes-nemisis' AND destination_bucket='dev-hermes-nemisis' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "NEMISIS Proccesed Files",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 20 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND new_file_key LIKE 'l1/%' AND source_bucket='dev-hermes-nemisis' AND destination_bucket='dev-hermes-nemisis' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "NEMISIS Proccesed Files",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND new_file_key LIKE 'ql/%' AND source_bucket='dev-hermes-nemisis' AND destination_bucket='dev-hermes-nemisis' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "MERIT Proccesed Files",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND source_bucket='dev-hermes-merit' AND destination_bucket='dev-hermes-merit' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "MERIT Proccesed Files",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 24 },
   "targets": [
    {
     "database": "\"sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND new_file_key LIKE 'l1/%' AND source_bucket='dev-hermes-merit' AND destination_bucket='dev-hermes-merit' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "MERIT Proccesed Files",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND new_file_key LIKE 'ql/%' AND source_bucket='dev-hermes-merit' AND destination_bucket='dev-hermes-merit' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "EEA Proccesed Files",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 29 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND new_file_key LIKE 'l1/%' AND source_bucket='dev-hermes-eea' AND destination_bucket='dev-hermes-eea' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "EEA Proccesed Files",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND new_file_key LIKE 'ql/%' AND source_bucket='dev-hermes-eea' AND destination_bucket='dev-hermes-eea' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "EEA Proccesed Files",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "database": "\"dev-sdc_aws_logs\"",
     "measure": "timestamp",
     "queryMode": "Metrics",
     "rawQuery": "SELECT time, file_key as original_file, new_file_key as processed_file FROM \"dev-sdc_aws_logs\".\"dev-sdc_aws_s3_bucket_log_table\" WHERE $__timeFilter AND source_bucket='dev-hermes-eea' AND destination_bucket='dev-hermes-eea' ORDER BY time DESC",
     "region": "default",
     "statistic": "Average",
     "table": "\"dev-sdc_aws_s3_bucket_log_table\""
    }
   ]
  },
  {
   "title": "Sorting Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{__aws_cloudwatch_log_group=\"/aws/lambda/dev_aws_sdc_sorting_lambda_function\"} |~ `(\\[INFO\\])|(\\[WARNING\\])|(\\[ERROR\\])` != \"Error sending Slack Notification\""
    }
   ]
  },
  {
   "title": "Processing Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "{__aws_cloudwatch_log_group=\"/aws/lambda/dev-sdc_aws_processing_lambda_function\"} |~ `(\\[INFO\\])|(\\[WARNING\\])|(\\[ERROR\\])` != \"Error sending Slack Notification\""
    }
   ]
  },
  {
   "title": "Errors in Sorting Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{__aws_cloudwatch_log_group=\"/aws/lambda/dev_aws_sdc_sorting_lambda_function\"} |= \"[ERROR]\" != \"Error sending Slack Notification\""
    }
   ]
  },
  {
   "title": "Errors in Processing Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "{__aws_cloudwatch_log_group=\"/aws/lambda/dev-sdc_aws_processing_lambda_function\"} |~ `(\\[ERROR\\])` != \"Error sending Slack Notification\""
    }
   ]
  },
  {
   "title": "Lambda Function Invocations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "dimensions": {
      "FunctionName": "dev_aws_sdc_sorting_lambda_function"
     },
     "label": "Sorting",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "FunctionName": "dev-sdc_aws_processing_lambda_function"
     },
     "label": "processing",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Instr. buckets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "dimensions": { "BucketName": "dev-hermes-eea" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BucketName": "dev-hermes-merit" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "BucketName": "dev-hermes-nemisis" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "BucketName": "dev-hermes-spani" },
     "metricName": "NumberOfObjects",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}