{
 "title": "SWPC (AWS TimeStream)",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "GOES XRS (Long 1-8 Angstrom)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawQuery": "SELECT time, measure_value::double FROM sampleDB.http\nWHERE measure_name = 'observed_flux' AND energy = '0.1-0.8nm'\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "GOES XRS (Short 0.5 to 5 Angstrom)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawQuery": "SELECT time, measure_value::double FROM sampleDB.http\nWHERE measure_name = 'observed_flux' AND energy = '0.05-0.4nm'\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "GOES Class",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT time, measure_value::double FROM sampleDB.http\nWHERE measure_name = 'observed_flux' AND energy = '0.1-0.8nm'\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Time of last point",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT time, measure_value::double FROM sampleDB.http\nWHERE measure_name = 'observed_flux' AND energy = '0.05-0.4nm'\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "DISCOVR Mag (GSE)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"sampleDB\"",
     "measure": "bx_gse",
     "rawQuery": "SELECT time, measure_value::double FROM sampleDB.http\nWHERE measure_name = 'bx_gse'\nORDER BY time DESC",
     "table": "\"http\""
    },
    {
     "rawQuery": "SELECT time, measure_value::double FROM sampleDB.http\r\nWHERE measure_name = 'by_gse'\r\nORDER BY time DESC"
    },
    {
     "rawQuery": "SELECT time, measure_value::double FROM sampleDB.http\r\nWHERE measure_name = 'bz_gse'\r\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "annolist",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "DISCOVR Mag (Bt)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"sampleDB\"",
     "measure": "bx_gse",
     "rawQuery": "SELECT time, measure_value::double FROM sampleDB.http\nWHERE measure_name = 'bt'\nORDER BY time DESC",
     "table": "\"http\""
    }
   ]
  }
 ]
}